/* ===========================================================================
   THE HELP CARDS (v229, 7 Oct 2026).

   Mike: "add in a help section ... how to do everything on the site and they
   can search" and "if we change anything we can just update the help docs too".

   THIS FILE IS THE WHOLE HELP SECTION. help.html only draws it.

   THE RULE: when a screen changes, change its card here IN THE SAME PUSH.
   A new feature gets a new card. A removed button loses its step.

   One card = one job.
     g     which group it sits under (see GROUPS)
     q     the question, the way a person would ask it
     s     the steps, in order. Button names are in "quotes", exactly as on screen.
     n     one short note under the steps (optional)
     go    [link, words on the button]  "Take me there" (optional)
     k     extra words people might search for (optional)

   Preschool simple. American spelling. No zeros. "could", not "should".
   ======================================================================== */
window.RM_HELP = {
  GROUPS: [
    ["start", "Getting started"],
    ["share", "Sharing"],
    ["photo", "Photos"],
    ["talk", "Comments and hearts"],
    ["people", "People and friends"],
    ["msg", "Messages"],
    ["group", "Groups"],
    ["spin", "Spins"],
    ["date", "Your sober date and coins"],
    ["today", "The Today page"],
    ["alert", "Alerts"],
    ["acct", "Your account"],
    ["safe", "Staying safe"]
  ],

  /* words that mean the same thing: searching one finds the others */
  SAME: [
    ["delete", "remove", "erase", "take off", "take down", "get rid"],
    ["photo", "photos", "picture", "pictures", "pic", "pics", "image", "selfie"],
    ["share", "post", "posting"],
    ["heart", "like", "love"],
    ["comment", "comments", "reply", "replies"],
    ["message", "messages", "dm", "chat", "text", "inbox"],
    ["alert", "alerts", "notification", "notifications", "push", "buzz", "bell"],
    ["sign in", "log in", "login", "signin"],
    ["sign out", "log out", "logout"],
    ["install", "download", "app", "home screen"],
    ["sober date", "clean date", "day count", "days", "counter"],
    ["coin", "coins", "chip", "chips", "medallion", "milestone"],
    ["block", "ban"],
    ["report", "flag"],
    ["spin", "spins", "video", "videos", "reel", "reels"],
    ["friend", "friends", "follow"],
    ["password", "passcode"],
    ["username", "name", "handle"],
    ["edit", "change", "fix", "update"],
    ["find", "search", "look up"],
    ["call", "phone", "video call"],
    ["quit", "leave", "close my account", "delete my account"]
  ],

  CARDS: [
    /* ------------------------------------------------ getting started */
    { g: "start", q: "How do I join?",
      s: ["Tap \"You\" at the bottom right.", "Tap \"Sign Up\".", "Pick a username and a password.", "Tick the box that says you are 18 or older.", "Tap \"I'm In\"."],
      n: "Your username is not your real name. No email or phone number in it.",
      go: ["/account.html", "Take me there"], k: "sign up create account register new" },
    { g: "start", q: "How do I sign in?",
      s: ["Tap \"You\" at the bottom right.", "Tap \"Sign In\".", "Type your username and password.", "Tap \"Sign In\"."],
      n: "You sign in with your username, not your email.",
      go: ["/account.html?signin=1", "Take me there"] },
    { g: "start", q: "I forgot my password",
      s: ["Tap \"You\", then \"Sign In\".", "Tap \"Forgot your password?\"", "Type your username and the email you confirmed.", "Tap \"Send My Code\".", "Type the code from your email and a new password.", "Tap \"Set My New Password\"."],
      n: "This only works if you confirmed an email. With no email there is no way to reset it.",
      go: ["/account.html?signin=1", "Take me there"], k: "reset lost" },
    { g: "start", q: "Why do I need an email for the Porch?",
      s: ["The Porch is for real people. One email, one person.", "Tap anything on the Porch and it asks for your email.", "Type it, tap \"Send my code\".", "Type the 6 numbers from the email, tap \"Confirm\"."],
      n: "Nobody on the Porch sees your email.", k: "code confirm verify" },
    { g: "start", q: "Why can't I share yet?",
      s: ["New accounts can look around right away.", "After 3 days you can share, comment, and add friends."],
      n: "It keeps the Porch safe from drive-by trouble.", k: "new account wait 3 days" },
    { g: "start", q: "How do I put this on my phone?",
      s: ["iPhone: open the site in Safari. Tap the Share button. Tap \"Add to Home Screen\". Tap \"Add\".", "Android: open the site in Chrome. Tap the three dots at the top right. Tap \"Add to Home screen\". Tap \"Install\"."],
      n: "It installs as a web based app. It is free.", k: "install download app home screen icon" },
    { g: "start", q: "What are the buttons at the bottom?",
      s: ["\"Today\" is your readings and the meme of the day.", "\"Porch\" is where people share.", "The gold \"+\" is how you share something.", "\"Invite\" shows a code a friend can scan.", "\"You\" is your account."],
      k: "bottom bar menu tabs" },
    { g: "start", q: "How do I invite a friend?",
      s: ["Tap \"Invite\" at the bottom.", "Let your friend point their phone camera at the code.", "Or tap \"Send link\" or \"Copy link\"."],
      k: "qr code tell a friend" },
    { g: "start", q: "Where is Help?",
      s: ["On the Porch: tap your picture at the bottom right, then \"Help\".", "Anywhere else: tap \"You\" at the bottom right, then \"Help\"."],
      k: "this page how to" },
    { g: "start", q: "What are the Porch rules?",
      s: ["On the Porch, tap your picture at the bottom right.", "Tap \"Edit profile\".", "Scroll to the bottom. Tap \"The Porch rules\"."],
      k: "house rules guidelines" },

    /* ------------------------------------------------ sharing */
    { g: "share", q: "How do I share something?",
      s: ["Tap the gold \"+\" at the bottom.", "Tap \"Say something\".", "Type what's on your mind.", "Tap \"Share\"."],
      n: "Everyone on the Porch will see it.",
      go: ["/feed/porch.html?new=1", "Take me there"], k: "post write new" },
    { g: "share", q: "How do I make a card?",
      s: ["Tap the gold \"+\", then \"Say something\".", "Type a short saying.", "Tap \"Card\" under your words.", "Tap a card you like, then \"Done\".", "Tap \"Share\"."],
      n: "Cards hold 150 letters.",
      go: ["/feed/porch.html?new=1", "Take me there"], k: "color background saying quote" },
    { g: "share", q: "What are tags?",
      s: ["When you write a share, tap \"Tags\".", "Pick what you are bringing: \"Experience\", \"Strength\", \"Hope\", or \"A question\".", "You can also tag a group you are in, or tap a hashtag.", "Tap \"Done\"."],
      n: "You can also just type # and a word.", k: "hashtag # label" },
    { g: "share", q: "How do I see it before I share it?",
      s: ["On the share screen, tap \"Preview\" at the top right.", "That is exactly what the Porch will see.", "Tap \"Share\" there, or go back to keep working."] },
    { g: "share", q: "How do I edit my share?",
      s: ["Tap the three dots on your share.", "Tap \"Edit this share\".", "Change your words, your tags, or your photos.", "Tap \"Save\"."],
      n: "It will say \"edited\" next to the time.", k: "change fix typo" },
    { g: "share", q: "How do I delete my share?",
      s: ["Tap the three dots on your share.", "Tap \"Delete this share\".", "Tap it one more time."],
      n: "It is gone for good.", k: "remove take down" },
    { g: "share", q: "How do I reshare someone's share?",
      s: ["Tap the two arrows under their share.", "Add a few words if you want.", "Tap \"Reshare\"."],
      n: "Their name stays on it.", k: "repost share again" },
    { g: "share", q: "How do I save a share for later?",
      s: ["Tap the three dots on the share.", "Tap \"Save this share\".", "To find it: tap your picture at the bottom right, then \"Saved shares\"."],
      n: "Only you can see your saved list.", k: "bookmark keep" },
    { g: "share", q: "How do I send a share to somebody?",
      s: ["Tap the paper plane under the share.", "\"Send in Misfit Messages\" sends it to a friend on the Porch.", "\"Share the link\" sends it by text, Messenger, or email."],
      k: "forward text link copy" },
    { g: "share", q: "It asked if I want to talk to a friend first",
      s: ["That shows up when your words sound heated.", "\"Text a friend\" lets you cool off first.", "\"Save it as a draft\" keeps your words for later.", "\"Share anyway\" posts it."],
      k: "pause angry draft" },

    /* ------------------------------------------------ photos */
    { g: "photo", q: "How do I share a photo?",
      s: ["Tap the gold \"+\" at the bottom.", "Tap \"Share photos\".", "Tap \"TAKE A PICTURE\" or \"PICK FROM MY PHONE\".", "Add some words if you want.", "Tap \"Share\"."],
      n: "A share holds up to 4 photos.",
      go: ["/feed/porch.html?new=1", "Take me there"], k: "upload camera picture" },
    { g: "photo", q: "It asked if everyone in the photo said OK",
      s: ["We check each photo for faces.", "If other people are in it, make sure they are OK with it.", "Tap \"Yes, everyone said OK\", or \"Pick a different photo\"."],
      n: "Anonymity matters here. Ask first.", k: "faces check permission" },
    { g: "photo", q: "It said \"Can't use this one\"",
      s: ["The photo check stopped it.", "Tap the X at the top left, or \"Pick a different photo\"."],
      k: "not allowed refused blocked photo" },
    { g: "photo", q: "How do I add or take off photos on a share I already made?",
      s: ["Tap the three dots on your share.", "Tap \"Edit this share\".", "Tap \"Add photos\" to add more.", "Tap the X on a photo to take it off.", "Tap \"Save\"."],
      n: "Not on a reshare, a Spin, or a card.", k: "edit photos more pictures remove" },
    { g: "photo", q: "Collage or swipe through?",
      s: ["Pick 2 to 4 photos and they become a collage.", "Under the picture, tap \"SWIPE THROUGH\" to show them one at a time.", "Tap \"COLLAGE\" to go back."] },
    { g: "photo", q: "How do I add stickers or a filter?",
      s: ["On a new photo share, tap \"Stickers\" or \"Filters\".", "Stickers: tap one to add it, drag it where you want, tap \"Done\".", "Filters: tap one, tap \"Done\"."],
      n: "A photo holds up to 8 stickers. These are for new shares only.", k: "decorate effects black and white" },
    { g: "photo", q: "How do I look at a photo up close?",
      s: ["Tap the photo.", "Swipe sideways to see the next one.", "Pinch or double tap to zoom.", "Tap the X to close."],
      n: "The pills on the picture send a quick comment in one tap.", k: "zoom big full screen viewer" },

    /* ------------------------------------------------ comments and hearts */
    { g: "talk", q: "How do I heart a share?",
      s: ["Tap the heart under it.", "Or double tap the photo.", "Tap the heart again to take it back."],
      k: "like love" },
    { g: "talk", q: "How do I comment?",
      s: ["Tap the speech bubble under a share.", "Type something kind.", "Tap \"Send\"."],
      k: "reply write" },
    { g: "talk", q: "What are the quick comments on a photo?",
      s: ["Tap a photo to open it.", "Tap a pill on the picture, like \"Love this\" or \"Proud of you\".", "It sends right away."],
      k: "fast one tap pills" },
    { g: "talk", q: "How do I reply to a comment?",
      s: ["Tap \"Reply\" under the comment.", "Type your reply.", "Tap \"Send\"."] },
    { g: "talk", q: "How do I edit or delete my comment?",
      s: ["Under your comment, tap \"Edit\" or \"Delete\".", "To edit: change the words, tap \"Save\".", "To delete: tap \"Delete this comment\", then tap it again."],
      k: "change remove fix" },
    { g: "talk", q: "How do I take someone's comment off my share?",
      s: ["Open the comments on your share.", "Tap the three dots on their comment.", "Tap \"Take this off my share\".", "Tap it one more time."],
      n: "It is gone for everybody. They are not told.", k: "delete remove hide comment on my post" },
    { g: "talk", q: "Why don't I see a number next to the heart?",
      s: ["Numbers show up at 2 and higher.", "Below that you just see the heart."],
      k: "count zero likes views" },

    /* ------------------------------------------------ people and friends */
    { g: "people", q: "How do I find somebody?",
      s: ["At the top of the Porch, tap \"Search the Porch\".", "Type their name or username.", "Tap them."],
      k: "search look up person" },
    { g: "people", q: "How do I find people near me?",
      s: ["Tap \"Search the Porch\".", "Tap \"People near me\".", "Let your phone share your location."],
      n: "It looks about 30 miles around you. Nobody ever sees where you are.", k: "local nearby location" },
    { g: "people", q: "How do I add a friend?",
      s: ["Tap their name or face.", "Tap \"Add Friend\".", "They get a request."],
      k: "friend request follow" },
    { g: "people", q: "How do I answer a friend request?",
      s: ["Tap your picture at the bottom right.", "Tap \"Friends\".", "Tap \"Be Friends\" or \"Not Now\"."],
      n: "If you tap \"Not Now\" they are not told.", k: "accept decline" },
    { g: "people", q: "How do I unfriend somebody?",
      s: ["Open their profile.", "Tap \"Friends\".", "Tap \"Unfriend\", then tap it again."],
      k: "remove friend" },
    { g: "people", q: "How do I see just my friends' shares?",
      s: ["At the top of the Porch, tap \"FRIENDS\"."] },
    { g: "people", q: "How do I change my picture, name, or bio?",
      s: ["On the Porch, tap your picture at the bottom right.", "Tap \"Edit profile\".", "Tap your picture to change it.", "Type in the name and bio boxes. It saves by itself.", "Tap \"I like it\"."],
      go: ["/feed/porch.html?u=me", "Take me to my profile"], k: "profile photo avatar about me" },
    { g: "people", q: "Who can see my profile?",
      s: ["Tap your picture, then \"Edit profile\".", "Find \"WHO CAN SEE MY PROFILE\".", "Pick \"Members only\" or \"Public\"."],
      n: "Your sober date is never on your profile.", k: "private public privacy" },
    { g: "people", q: "How do I share my profile?",
      s: ["Tap your picture at the bottom right.", "Tap \"Copy\" next to your link.", "Paste it anywhere."],
      k: "link address" },

    /* ------------------------------------------------ messages */
    { g: "msg", q: "How do I message somebody?",
      s: ["On the Porch, tap the chat bubble at the top right.", "Tap \"New\".", "Tap a friend.", "Type your message and tap the arrow."],
      n: "You can message friends only.", k: "dm chat text private" },
    { g: "msg", q: "How do I unsend a message?",
      s: ["Tap your message.", "Tap \"Unsend\", then tap it again."],
      n: "It is gone for both of you.", k: "delete take back" },
    { g: "msg", q: "How do I start a group chat?",
      s: ["Tap the chat bubble at the top right.", "Tap \"Group\".", "Pick your friends.", "Tap \"Start the chat\"."],
      n: "A group chat holds 12 people. Friends only." },
    { g: "msg", q: "How do I call a friend?",
      s: ["Open your chat with them.", "Tap the phone or the video camera at the top."],
      n: "Friends only. Calls are never recorded.", k: "voice video call" },
    { g: "msg", q: "What's a Poof?",
      s: ["A Poof is one picture a friend can open once.", "After 10 seconds it is gone.", "To turn it on: tap your picture, \"Edit profile\", then \"Turn Poof on\"."],
      n: "You both need it turned on.", k: "disappearing photo" },

    /* ------------------------------------------------ groups */
    { g: "group", q: "How do I join a group?",
      s: ["At the top of the Porch, tap \"GROUPS\".", "Find one you like.", "Tap \"Join\" or \"Ask to join\"."],
      go: ["/feed/porch.html?groups=1", "Take me there"] },
    { g: "group", q: "How do I share in a group?",
      s: ["Open the group.", "Tap \"+ Share here\".", "Write your share and tap \"Share\"."],
      n: "Only people in the group will see it." },
    { g: "group", q: "How do I leave a group?",
      s: ["Open the group.", "Tap the three dots.", "Tap \"Leave this group\", then tap it again."],
      k: "quit exit" },
    { g: "group", q: "How do I start a group?",
      s: ["Tap \"GROUPS\", then \"+ Apply to start a group\".", "Fill in the name and what it is for.", "Pick a friend to help you keep it.", "Tap \"Apply\"."],
      n: "You need 30 days on the Porch first. A real person looks at each one.", k: "create new make" },

    /* ------------------------------------------------ spins */
    { g: "spin", q: "What's a Spin?",
      s: ["A Spin is a short video.", "Watch them in the circles at the top of the Porch, or tap \"SPINS\".", "Swipe up for the next one."],
      k: "video reel story" },
    { g: "spin", q: "How do I make a Spin?",
      s: ["Tap the gold \"+\" at the bottom.", "Tap \"Give it a spin\".", "Tap \"Record\" or \"Upload\".", "Pick a style, add words or music if you want.", "Tap \"Make my Spin\", then \"Post Spin\"."],
      n: "A Spin is up to 15 seconds and lasts 30 days.",
      go: ["/feed/porch.html?new=1", "Take me there"], k: "video record upload" },
    { g: "spin", q: "How do I keep a Spin longer than 30 days?",
      s: ["Open your Spin.", "Tap the three dots.", "Tap \"Pin to my profile\"."],
      n: "You can pin up to 3.", k: "pin save keep" },
    { g: "spin", q: "How do I delete my Spin?",
      s: ["Open your Spin.", "Tap the three dots.", "Tap \"Delete this Spin\", then tap it again."],
      k: "remove" },

    /* ------------------------------------------------ sober date and coins */
    { g: "date", q: "How do I set or change my sober date?",
      s: ["Tap \"Sober Since\" on the bar above the bottom buttons.", "Spin the wheels to your date.", "Tap \"Save\"."],
      n: "It is just for you. Nobody sees it unless you share it.", k: "clean date day count reset relapse" },
    { g: "date", q: "How do I share my sober date or a milestone?",
      s: ["Tap the coin on the bar above the bottom buttons.", "Tap \"Share to the Porch\", or \"Share my card\" to send it somewhere else."],
      n: "Your name is not on the card.",
      go: ["/sober-date.html", "Take me there"], k: "anniversary birthday celebrate" },
    { g: "date", q: "Where are my coins?",
      s: ["Tap \"Today\" at the bottom.", "Scroll down to \"Your Corner\".", "Tap \"Your Coins\"."],
      n: "You get one at 24 hours, 30, 60, and 90 days, 6 months, and every year.",
      go: ["/coins.html", "Take me there"], k: "chips medallions" },
    { g: "date", q: "What's the Survival Pile?",
      s: ["Little cards you earn between the big coins.", "Tap \"Today\", scroll to \"Your Corner\", tap \"Your Survival Pile\"."],
      go: ["/survival-pile.html", "Take me there"], k: "cards milestones" },

    /* ------------------------------------------------ today */
    { g: "today", q: "What's on the Today page?",
      s: ["Today's reading.", "Your daily stack of readings.", "The meme of the day.", "\"More on the shelf\": Listen, Fun, and Tools.", "\"Your Corner\": your coins and milestones."],
      go: ["/index.html", "Take me there"], k: "home readings daily" },
    { g: "today", q: "How do I pick my daily readings?",
      s: ["On the Today page, find \"Your daily stack\".", "Tap \"Edit\".", "Tap the minus to take one off. Tap the plus to put it back.", "Tap the arrow to move one up."],
      go: ["/index.html", "Take me there"], k: "stack reflections arrange" },
    { g: "today", q: "Where did Listen, Fun, and Tools go?",
      s: ["Tap \"Today\" at the bottom.", "Scroll to \"More on the shelf\".", "Tap \"Listen\", \"Fun\", or \"Tools\"."],
      go: ["/index.html", "Take me there"], k: "audio speakers audiobooks games inventory moved" },
    { g: "today", q: "What's in Tools?",
      s: ["Nightly Inventory.", "Burn Pad.", "Fear Compass.", "Gratitude.", "The Untangler.", "The Book Shelf."],
      go: ["/tools.html", "Take me there"], k: "step work journal big book" },
    { g: "today", q: "How do I share the meme of the day?",
      s: ["On the Today page, tap \"Meme of the Day\".", "Tap \"Share to the Porch\", \"Share this one\", or \"Share the link\"."],
      go: ["/meme.html", "Take me there"], k: "funny picture" },

    /* ------------------------------------------------ alerts */
    { g: "alert", q: "How do I turn alerts on or off?",
      s: ["On the Porch, tap the bell at the top right.", "Tap the switch that says \"Alerts OFF\" or \"Alerts ON\".", "If your phone asks, tap \"Allow\"."],
      go: ["/feed/porch.html?notes=1", "Take me there"], k: "notifications push buzz" },
    { g: "alert", q: "Alerts won't turn on with my iPhone",
      s: ["Alerts on an iPhone only work when the site is on your Home Screen.", "Put it on your Home Screen first.", "Open it from that icon, then turn alerts on."],
      k: "ios apple notifications not working" },
    { g: "alert", q: "How do I turn the sounds off?",
      s: ["On the Porch, tap the bell at the top right.", "Tap \"Sounds on\" so it says \"Sounds off\"."],
      k: "mute quiet noise" },

    /* ------------------------------------------------ account */
    { g: "acct", q: "How do I sign out?",
      s: ["Tap \"You\" at the bottom right.", "Tap \"Sign Out\"."],
      n: "On the Porch: tap your picture, then \"Sign out\".", k: "log out" },
    { g: "acct", q: "How do I switch accounts?",
      s: ["Hold your finger on \"You\" for a second.", "Tap the account you want.", "Or tap \"Add account\"."],
      k: "second account another" },
    { g: "acct", q: "How do I take a break?",
      s: ["On the Porch, tap your picture at the bottom right.", "Tap \"Edit profile\".", "Scroll to the bottom. Tap \"Delete my account\".", "Tap \"Take a break\"."],
      n: "A break hides your profile and shares. Nothing is erased. You can come back.", k: "pause hide deactivate" },
    { g: "acct", q: "How do I delete my account?",
      s: ["On the Porch, tap your picture at the bottom right.", "Tap \"Edit profile\".", "Scroll to the bottom. Tap \"Delete my account\".", "Wait for the count, tap \"Delete my account\", then tap it again."],
      n: "This can't be undone. Everything is wiped and your username is retired for good.", k: "close quit remove erase" },

    /* ------------------------------------------------ staying safe */
    { g: "safe", q: "I'm having a hard time right now",
      s: ["Call or text 988. A real person answers, day or night.", "If somebody is in danger right now, call 911."],
      go: ["tel:988", "Call 988"], k: "crisis help suicide emergency relapse drink use" },
    { g: "safe", q: "How do I report something?",
      s: ["Tap the three dots on the share or comment.", "Tap \"Report this share\" or \"Report this comment\".", "Tap what is wrong with it."],
      n: "It is hidden right away. A real person will look at it.", k: "flag bad abuse" },
    { g: "safe", q: "What happens after I report something?",
      s: ["It is hidden for everybody.", "A moderator looks at it.", "They take it down for good, or put it back."],
      n: "The person is not told who reported it." },
    { g: "safe", q: "How do I mute somebody?",
      s: ["Tap the three dots on their share.", "Tap \"Mute\"."],
      n: "You won't see their shares or Spins. They are not told.", k: "hide quiet" },
    { g: "safe", q: "How do I block somebody?",
      s: ["Tap the three dots on their share.", "Tap \"Block\", then tap it again."],
      n: "You won't see each other at all.", k: "ban stop" },
    { g: "safe", q: "How do I unblock or unmute somebody?",
      s: ["Tap your picture at the bottom right.", "Tap \"Edit profile\".", "Scroll to the bottom. Tap \"Blocked & muted\".", "Tap \"Unblock\" or \"Unmute\"."] },
    { g: "safe", q: "Who can see my sober date?",
      s: ["Nobody. It is just for you.", "It only goes out if you choose to share it."],
      k: "private anonymous" },
    { g: "safe", q: "Is my email or real name shown?",
      s: ["No. People see your username.", "You can add a name people see, but you don't have to."],
      k: "anonymous privacy private" }
  ]
};
