/* A self-contained QR encoder.

   The same encoder the Shield's site uses, lifted here so the share sheet
   can draw its own code rather than ship a picture that goes stale the day
   the address changes. Nothing is fetched and nothing is generated by a
   third party, which also means the code works with no signal at all.

   Byte mode, error correction level M (recovers from ~15% damage, which is
   what a QR on a truck door needs), versions 1 through 20 chosen
   automatically by length. No dependencies, no network, works offline.

   window.RM_QR.svg(text, options) -> an SVG string.
*/
(function (root) {
  "use strict";

  /* ---- Galois field arithmetic over GF(256), the basis of Reed-Solomon ---- */
  var EXP = new Uint8Array(512), LOG = new Uint8Array(256);
  (function () {
    var x = 1;
    for (var i = 0; i < 255; i++) {
      EXP[i] = x; LOG[x] = i;
      x <<= 1;
      if (x & 0x100) x ^= 0x11D;      // the QR standard's primitive polynomial
    }
    for (var j = 255; j < 512; j++) EXP[j] = EXP[j - 255];
  })();
  function mul(a, b) { return (a === 0 || b === 0) ? 0 : EXP[LOG[a] + LOG[b]]; }

  /* The generator polynomial for n error-correction codewords:
     the product of (x - a^i) for i = 0..n-1, highest power first.

     Coefficients are stored highest-degree-first, so multiplying by x
     keeps index j and multiplying by the constant a^i moves it to j+1.
     Swapping those two lines still produces a plausible-looking
     polynomial and every symbol fails its error correction. */
  function genPoly(n) {
    var poly = [1];
    for (var i = 0; i < n; i++) {
      var next = new Array(poly.length + 1).fill(0);
      for (var j = 0; j < poly.length; j++) {
        next[j] ^= poly[j];                        // multiply by x
        next[j + 1] ^= mul(poly[j], EXP[i]);       // multiply by a^i
      }
      poly = next;
    }
    return poly;
  }

  function ecBytes(data, n) {
    var poly = genPoly(n);
    var rem = new Array(n).fill(0);
    for (var i = 0; i < data.length; i++) {
      var factor = data[i] ^ rem[0];
      rem.shift(); rem.push(0);
      if (factor !== 0) for (var j = 0; j < n; j++) rem[j] ^= mul(poly[j + 1], factor);
    }
    return rem;
  }

  /* ---- Capacity tables, level M only, versions 1-20 ----
     [ total codewords, ec codewords per block, group1 blocks, group2 blocks ] */
  var VERSIONS = [
    null,
    [  26, 10,  1, 0], [  44, 16,  1, 0], [  70, 26,  1, 0], [ 100, 18,  2, 0],
    [ 134, 24,  2, 0], [ 172, 16,  4, 0], [ 196, 18,  4, 0], [ 242, 22,  2, 2],
    [ 292, 22,  3, 2], [ 346, 26,  4, 1], [ 404, 30,  1, 4], [ 466, 22,  6, 2],
    [ 532, 22,  8, 1], [ 581, 24,  4, 5], [ 655, 24,  5, 5], [ 733, 28,  7, 3],
    [ 815, 28, 10, 1], [ 901, 26,  9, 4], [ 991, 26,  3, 11], [1085, 26,  3, 13]
  ];
  /* Alignment pattern centers per version. */
  var ALIGN = [
    null, [], [6,18], [6,22], [6,26], [6,30], [6,34], [6,22,38], [6,24,42],
    [6,26,46], [6,28,50], [6,30,54], [6,32,58], [6,34,62], [6,26,46,66],
    [6,26,48,70], [6,26,50,74], [6,30,54,78], [6,30,56,82], [6,30,58,86],
    [6,34,62,90]
  ];

  function utf8(str) {
    var out = [], i, c;
    for (i = 0; i < str.length; i++) {
      c = str.charCodeAt(i);
      if (c < 0x80) out.push(c);
      else if (c < 0x800) out.push(0xC0 | (c >> 6), 0x80 | (c & 63));
      else if (c >= 0xD800 && c <= 0xDBFF) {          // surrogate pair
        c = 0x10000 + ((c & 0x3FF) << 10) + (str.charCodeAt(++i) & 0x3FF);
        out.push(0xF0 | (c >> 18), 0x80 | ((c >> 12) & 63), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63));
      } else out.push(0xE0 | (c >> 12), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63));
    }
    return out;
  }

  function build(text) {
    var bytes = utf8(text);

    /* Pick the smallest version the data fits in. The byte-mode length
       field is 8 bits up to version 9 and 16 bits from version 10, which
       is why the header cost changes partway down. */
    var ver = 0, spec, capacity;
    for (var v = 1; v <= 20; v++) {
      spec = VERSIONS[v];
      var blocks = spec[2] + spec[3];
      var dataCodewords = spec[0] - spec[1] * blocks;
      var header = 4 + (v < 10 ? 8 : 16);
      if (bytes.length * 8 + header <= dataCodewords * 8) { ver = v; capacity = dataCodewords; break; }
    }
    if (!ver) throw new Error("too much data for a version 20 QR");
    spec = VERSIONS[ver];

    /* ---- bit stream ---- */
    var bits = [];
    function push(val, len) { for (var i = len - 1; i >= 0; i--) bits.push((val >> i) & 1); }
    push(4, 4);                                   // byte mode
    push(bytes.length, ver < 10 ? 8 : 16);
    for (var i = 0; i < bytes.length; i++) push(bytes[i], 8);

    var total = capacity * 8;
    for (var t = 0; t < 4 && bits.length < total; t++) bits.push(0);   // terminator
    while (bits.length % 8) bits.push(0);
    var data = [];
    for (var b = 0; b < bits.length; b += 8) {
      var byte = 0;
      for (var k = 0; k < 8; k++) byte = (byte << 1) | bits[b + k];
      data.push(byte);
    }
    var pad = [0xEC, 0x11], p = 0;
    while (data.length < capacity) data.push(pad[p++ % 2]);

    /* ---- split into blocks, compute EC, interleave ---- */
    var g1 = spec[2], g2 = spec[3], ecLen = spec[1];
    var totalBlocks = g1 + g2;
    var short_ = Math.floor(capacity / totalBlocks);
    var dataBlocks = [], ecBlocks = [], pos = 0;
    for (var n = 0; n < totalBlocks; n++) {
      var len = short_ + (n >= g1 ? 1 : 0);
      var blk = data.slice(pos, pos + len); pos += len;
      dataBlocks.push(blk);
      ecBlocks.push(ecBytes(blk, ecLen));
    }
    var out = [], maxLen = short_ + (g2 ? 1 : 0);
    for (var c = 0; c < maxLen; c++)
      for (var d = 0; d < totalBlocks; d++)
        if (c < dataBlocks[d].length) out.push(dataBlocks[d][c]);
    for (var e = 0; e < ecLen; e++)
      for (var f = 0; f < totalBlocks; f++) out.push(ecBlocks[f][e]);

    return { version: ver, codewords: out };
  }

  /* ---- the module grid ---- */
  function matrix(ver, codewords) {
    var size = ver * 4 + 17;
    var m = [], reserved = [];
    for (var i = 0; i < size; i++) {
      m.push(new Array(size).fill(0));
      reserved.push(new Array(size).fill(false));
    }
    function set(r, c, v) { m[r][c] = v ? 1 : 0; reserved[r][c] = true; }

    function finder(r, c) {
      for (var dr = -1; dr <= 7; dr++) for (var dc = -1; dc <= 7; dc++) {
        var rr = r + dr, cc = c + dc;
        if (rr < 0 || cc < 0 || rr >= size || cc >= size) continue;
        var on = dr >= 0 && dr <= 6 && dc >= 0 && dc <= 6 &&
                 (dr === 0 || dr === 6 || dc === 0 || dc === 6 ||
                  (dr >= 2 && dr <= 4 && dc >= 2 && dc <= 4));
        set(rr, cc, on);
      }
    }
    finder(0, 0); finder(0, size - 7); finder(size - 7, 0);

    for (var t = 8; t < size - 8; t++) {              // timing patterns
      set(6, t, t % 2 === 0);
      set(t, 6, t % 2 === 0);
    }

    var centers = ALIGN[ver];                          // alignment patterns
    for (var a = 0; a < centers.length; a++) for (var b = 0; b < centers.length; b++) {
      var ar = centers[a], ac = centers[b];
      if ((ar <= 8 && ac <= 8) || (ar <= 8 && ac >= size - 9) || (ar >= size - 9 && ac <= 8)) continue;
      for (var y = -2; y <= 2; y++) for (var x = -2; x <= 2; x++)
        set(ar + y, ac + x, Math.max(Math.abs(y), Math.abs(x)) !== 1);
    }

    set(size - 8, 8, 1);                               // the always-dark module

    /* Reserve the format-information areas EXACTLY. Over-reserving here is
       silent and fatal: every extra cell shifts the whole zig-zag data
       placement by one and the symbol stops decoding with no clue why. */
    for (var f = 0; f <= 8; f++) { reserved[8][f] = true; reserved[f][8] = true; }
    for (var f2 = size - 8; f2 < size; f2++) { reserved[8][f2] = true; reserved[f2][8] = true; }

    if (ver >= 7) {                                    // version information
      var vinfo = versionBits(ver);
      for (var v2 = 0; v2 < 18; v2++) {
        var bit = (vinfo >> v2) & 1;
        set(Math.floor(v2 / 3), size - 11 + (v2 % 3), bit);
        set(size - 11 + (v2 % 3), Math.floor(v2 / 3), bit);
      }
    }

    /* Zig-zag placement, right to left, skipping the vertical timing column. */
    var bitIndex = 0, dir = -1, row = size - 1;
    for (var col = size - 1; col > 0; col -= 2) {
      if (col === 6) col--;
      while (true) {
        for (var o = 0; o < 2; o++) {
          var cc2 = col - o;
          if (!reserved[row][cc2]) {
            var bv = 0;
            if (bitIndex < codewords.length * 8)
              bv = (codewords[bitIndex >> 3] >> (7 - (bitIndex & 7))) & 1;
            bitIndex++;
            m[row][cc2] = bv;
          }
        }
        row += dir;
        if (row < 0 || row >= size) { row -= dir; dir = -dir; break; }
      }
    }
    return { size: size, m: m, reserved: reserved };
  }

  var MASKS = [
    function (r, c) { return (r + c) % 2 === 0; },
    function (r)    { return r % 2 === 0; },
    function (r, c) { return c % 3 === 0; },
    function (r, c) { return (r + c) % 3 === 0; },
    function (r, c) { return (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0; },
    function (r, c) { return (r * c) % 2 + (r * c) % 3 === 0; },
    function (r, c) { return ((r * c) % 2 + (r * c) % 3) % 2 === 0; },
    function (r, c) { return ((r + c) % 2 + (r * c) % 3) % 2 === 0; }
  ];

  function formatBits(mask) {
    /* Level M is 0b00. 5 data bits, BCH(15,5), then the standard XOR. */
    var data = (0 << 3) | mask;
    var rem = data;
    for (var i = 0; i < 10; i++) rem = (rem << 1) ^ (((rem >> 9) & 1) * 0x537);
    return ((data << 10) | rem) ^ 0x5412;
  }
  function versionBits(ver) {
    var rem = ver;
    for (var i = 0; i < 12; i++) rem = (rem << 1) ^ (((rem >> 11) & 1) * 0x1F25);
    return (ver << 12) | rem;
  }

  function penalty(m, size) {
    var score = 0, r, c, run, i;
    for (r = 0; r < size; r++) {                       // rule 1, rows
      run = 1;
      for (c = 1; c < size; c++) {
        if (m[r][c] === m[r][c - 1]) { run++; if (run === 5) score += 3; else if (run > 5) score++; }
        else run = 1;
      }
    }
    for (c = 0; c < size; c++) {                       // rule 1, columns
      run = 1;
      for (r = 1; r < size; r++) {
        if (m[r][c] === m[r - 1][c]) { run++; if (run === 5) score += 3; else if (run > 5) score++; }
        else run = 1;
      }
    }
    for (r = 0; r < size - 1; r++) for (c = 0; c < size - 1; c++)   // rule 2, 2x2 blocks
      if (m[r][c] === m[r][c+1] && m[r][c] === m[r+1][c] && m[r][c] === m[r+1][c+1]) score += 3;

    var PAT = [1,0,1,1,1,0,1,0,0,0,0];                 // rule 3, finder-like runs
    function hit(get, len) {
      var s = 0;
      for (var a = 0; a + 11 <= len; a++) {
        var ok = true;
        for (var b = 0; b < 11; b++) if (get(a + b) !== PAT[b]) { ok = false; break; }
        if (ok) s += 40;
        ok = true;
        for (var d = 0; d < 11; d++) if (get(a + d) !== PAT[10 - d]) { ok = false; break; }
        if (ok) s += 40;
      }
      return s;
    }
    for (r = 0; r < size; r++) score += hit(function (i2) { return m[r][i2]; }, size);
    for (c = 0; c < size; c++) score += hit(function (i2) { return m[i2][c]; }, size);

    var dark = 0;                                      // rule 4, dark/light balance
    for (r = 0; r < size; r++) for (c = 0; c < size; c++) dark += m[r][c];
    var pct = dark * 100 / (size * size);
    score += Math.floor(Math.abs(pct - 50) / 5) * 10;
    return score;
  }

  function encode(text) {
    var built = build(text);
    var base = matrix(built.version, built.codewords);
    var size = base.size;
    var best = null, bestScore = Infinity;

    for (var mask = 0; mask < 8; mask++) {
      var g = base.m.map(function (row) { return row.slice(); });
      for (var r = 0; r < size; r++) for (var c = 0; c < size; c++)
        if (!base.reserved[r][c] && MASKS[mask](r, c)) g[r][c] ^= 1;

      /* Format info, written twice. Bit 0 is the LSB.

         Copy 1 wraps the top-left finder: bits 0-5 along row 8, then (8,7),
         (8,8), (7,8), then bits 9-14 up column 8 skipping the timing row.

         Copy 2 is split: bits 0-6 up column 8 from the bottom, bits 7-14
         along row 8 from the right.

         Getting these transposed puts a valid-looking pattern in the wrong
         place and nothing decodes -- which is exactly what happened here
         the first time. */
      var fmt = formatBits(mask);
      for (var i = 0; i < 15; i++) {
        /* MOST significant bit first: position 0 in the sequence below
           carries bit 14 of the format value, not bit 0. Writing it the
           other way round produces a symbol that looks perfectly normal
           and decodes in nothing. */
        var bit = (fmt >> (14 - i)) & 1;

        if (i < 6)       g[8][i] = bit;
        else if (i === 6) g[8][7] = bit;
        else if (i === 7) g[8][8] = bit;
        else if (i === 8) g[7][8] = bit;
        else              g[14 - i][8] = bit;

        if (i < 7) g[size - 1 - i][8] = bit;
        else       g[8][size - 15 + i] = bit;
      }
      g[size - 8][8] = 1;                              // the dark module is fixed

      var s = penalty(g, size);
      if (s < bestScore) { bestScore = s; best = g; }
    }
    return { size: size, modules: best };
  }

  /* ---- rendering ----
     border:4 is the quiet zone the spec requires. A QR with no white margin
     around it scans in a preview and then fails on a real camera, which is
     the worst possible way to find out. */
  function svg(text, opts) {
    opts = opts || {};
    var q = encode(text);
    var border = opts.border == null ? 4 : opts.border;
    var dim = q.size + border * 2;
    var dark = opts.dark || "#022b43";
    var light = opts.light || "#ffffff";

    var path = "";
    for (var r = 0; r < q.size; r++) {
      var c = 0;
      while (c < q.size) {
        if (!q.modules[r][c]) { c++; continue; }
        var run = 0;
        while (c + run < q.size && q.modules[r][c + run]) run++;
        path += "M" + (c + border) + " " + (r + border) + "h" + run + "v1h-" + run + "z";
        c += run;
      }
    }
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ' + dim + ' ' + dim + '" ' +
           'shape-rendering="crispEdges" role="img" aria-label="QR code">' +
           '<rect width="' + dim + '" height="' + dim + '" fill="' + light + '"/>' +
           '<path d="' + path + '" fill="' + dark + '"/></svg>';
  }

  root.RM_QR = { svg: svg, encode: encode };
})(typeof window !== "undefined" ? window : globalThis);
